### ISSUE TITLE
Qual ferramenta 

### ISSUE THREAD

**Issue by ArthurFuchsReis** [IolandaPereira/JavaIniciantes#1]
Olá, tudo bem? qual é a ferramenta você está fazendo os seus programas de java?

Atenciosamente,

@ArthurFuchsReis

**Comment by IolandaPereira** [comment]
Olá, tudo bem!!
Eu utilizo o NetBeans IDE versão 8.2 acho bem simples de utilizar. Com ele, podemos desenvolver aplicações para desktop, dispositivos móveis e web.

**Comment by IolandaPereira** [comment]
Olá, @ArthurFuchsReis. Tudo bem!
Eu utilizo o NetBeans, acho bem simples de utilizar. Com ele, podemos desenvolver aplicações para desktop, dispositivos móveis e web.

**Comment by ArthurFuchsReis** [comment]
@IolandaPereira ,

Que legal! gosto muito de netbeans. Acabei de fazer um projeto com a minha turma usando o java.

Fiquei responsável pelo front-end.

Eu estava pensando de formar um grupo de estudo de Java. 

Você gostaria de participar?

Att,

@ArthurFuchsReis

**Comment by IolandaPereira** [comment]
Gostaria sim!! Sempre bom compartilhar conhecimento.

**Comment by ArthurFuchsReis** [comment]
É verdade. Se você puder me addiciona no whatsapp (11)971201041 para nós conversarmos melhor a respeito. Pode ser? ou se você quiser outro meio de contato, aceito sugestão.
